### PR TITLE
refactor: wallet connect

### PR DESCRIPTION
**Pull request by kingsleydon**
Allowing selecting wallets among Polkadot{.js}, Talisman and SubWallet.

#19 #17 should be fixed along

### CODE REVIEW

**Comment by h4x3rotab** [comment]
> Unable to connect wallet using imToken app after this merge

I thought it was never supported?

**Comment by zozyo** [comment]
> > Unable to connect wallet using imToken app after this merge
> 
> I thought it was never supported?

It was supported. 

Tutorial on the forum.
https://forum.phala.network/t/topic/3438

**Comment by h4x3rotab** [comment]
Interesting. We talked to imtoken many times to add the support to Khala, and finally it's addressed. Let's try to fix it.

**Comment by h4x3rotab** [comment]
@zozyo Please don't forget to ask for a tip once the bug is fixed

**Comment by zozyo** [comment]
> Interesting. We talked to imtoken many times to add the support to Khala, and finally it's addressed. Let's try to fix it.




imToken seems has Polkadot{.js} installed, but not work after this merge.

**Comment by zozyo** [comment]
#

> @zozyo Please don't forget to ask for a tip once the bug is fixed

Tip asked

**Pull request merged**
